baseURL = 'https://jeffyip.github.io'
languageCode = 'en-us'
title = "Jeff Yip's Blog"
theme = 'hugo-theme-stack'
defaultContentLanguage = 'en'

[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"
